import { useEffect, useState, type FormEvent } from 'react'
import { Edit3, Plus, Save, Trash2, X } from 'lucide-react'
import { supabase } from '../../lib/supabase'
import { AdminHeader, AdminNotice, EmptyState, dangerButtonClass, inputClass, labelClass, primaryButtonClass, secondaryButtonClass } from './AdminUi'

type Category = { id: string; branch_id: string | null; name: string; description: string | null; image_url: string | null; sort_order: number; is_active: boolean }
type Branch = { id: string; name: string }
const empty = { name: '', branch_id: '', description: '', image_url: '', sort_order: '0', is_active: true }

export function AdminCategoriesPage() {
  const [items, setItems] = useState<Category[]>([]); const [branches, setBranches] = useState<Branch[]>([])
  const [form, setForm] = useState(empty); const [editingId, setEditingId] = useState<string | null>(null); const [open, setOpen] = useState(false)
  const [error, setError] = useState<string | null>(null); const [success, setSuccess] = useState<string | null>(null); const [saving, setSaving] = useState(false)
  const load = async () => { const client = supabase; if (!client) return; const [a,b] = await Promise.all([client.from('menu_categories').select('id, branch_id, name, description, image_url, sort_order, is_active').order('sort_order'), client.from('branches').select('id,name').order('name')]); if (a.error || b.error) setError(a.error?.message ?? b.error?.message ?? 'خطأ'); else { setItems(a.data ?? []); setBranches(b.data ?? []) } }
  useEffect(() => { void load() }, [])
  const edit = (x: Category) => { setEditingId(x.id); setForm({ name:x.name, branch_id:x.branch_id ?? '', description:x.description ?? '', image_url:x.image_url ?? '', sort_order:String(x.sort_order), is_active:x.is_active }); setOpen(true) }
  const save = async (e: FormEvent) => { e.preventDefault(); const client=supabase; if(!client)return; if(!form.name.trim()){setError('اسم التصنيف مطلوب');return} setSaving(true); const payload={name:form.name.trim(),branch_id:form.branch_id||null,description:form.description.trim()||null,image_url:form.image_url.trim()||null,sort_order:Number(form.sort_order)||0,is_active:form.is_active}; const r=editingId?await client.from('menu_categories').update(payload).eq('id',editingId):await client.from('menu_categories').insert(payload); if(r.error)setError(r.error.message);else{setSuccess('تم الحفظ');setOpen(false);setEditingId(null);setForm(empty);await load()}setSaving(false) }
  const remove=async(x:Category)=>{if(!confirm(`حذف تصنيف ${x.name}؟ المنتجات التابعة له بتصير بدون تصنيف.`))return;const client=supabase;if(!client)return;const r=await client.from('menu_categories').delete().eq('id',x.id);if(r.error)setError(r.error.message);else{setSuccess('تم الحذف');await load()}}
  return <section className="p-4 sm:p-6"><AdminHeader title="إدارة التصنيفات" description="نظّم المنيو إلى أقسام واضحة." action={<button className={primaryButtonClass} onClick={()=>{setEditingId(null);setForm(empty);setOpen(true)}}><Plus className="ml-2 inline size-4"/>إضافة تصنيف</button>}/><AdminNotice error={error} success={success}/>{open&&<form onSubmit={(e)=>void save(e)} className="mt-5 rounded-3xl bg-white p-5 shadow-sm"><div className="mb-4 flex justify-between"><h2 className="font-black">{editingId?'تعديل التصنيف':'تصنيف جديد'}</h2><button type="button" onClick={()=>setOpen(false)}><X className="size-5"/></button></div><div className="grid gap-4 md:grid-cols-2"><label><span className={labelClass}>الاسم *</span><input className={inputClass} value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></label><label><span className={labelClass}>الفرع</span><select className={inputClass} value={form.branch_id} onChange={e=>setForm({...form,branch_id:e.target.value})}><option value="">كل الفروع</option>{branches.map(b=><option key={b.id} value={b.id}>{b.name}</option>)}</select></label><label className="md:col-span-2"><span className={labelClass}>الوصف</span><textarea className={inputClass} value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/></label><label><span className={labelClass}>رابط الصورة</span><input className={inputClass} dir="ltr" value={form.image_url} onChange={e=>setForm({...form,image_url:e.target.value})}/></label><label><span className={labelClass}>الترتيب</span><input className={inputClass} type="number" value={form.sort_order} onChange={e=>setForm({...form,sort_order:e.target.value})}/></label><label className="flex items-center gap-2"><input type="checkbox" checked={form.is_active} onChange={e=>setForm({...form,is_active:e.target.checked})}/>نشط وظاهر</label></div><div className="mt-5 flex gap-3"><button disabled={saving} className={primaryButtonClass}><Save className="ml-2 inline size-4"/>حفظ</button><button type="button" className={secondaryButtonClass} onClick={()=>setOpen(false)}>إلغاء</button></div></form>}<div className="mt-5 grid gap-3 md:grid-cols-2">{items.length===0?<div className="md:col-span-2"><EmptyState>ما فيه تصنيفات حتى الآن.</EmptyState></div>:items.map(x=><article key={x.id} className="rounded-2xl bg-white p-4 shadow-sm"><div className="flex justify-between gap-4"><div><h3 className="font-black">{x.name}</h3><p className="text-sm text-vibes-600">{branches.find(b=>b.id===x.branch_id)?.name??'كل الفروع'} · ترتيب {x.sort_order}</p>{!x.is_active&&<span className="text-xs text-red-600">مخفي</span>}</div><div className="flex gap-2"><button className={secondaryButtonClass} onClick={()=>edit(x)}><Edit3 className="size-4"/></button><button className={dangerButtonClass} onClick={()=>void remove(x)}><Trash2 className="size-4"/></button></div></div></article>)}</div></section>
}
